### ISSUE TITLE
gedis support for non JSX clients

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_core#58]
## specs

- cmd FORMAT_CONFIGURE ($format)
    = $format = JSON or MSGPACK
- cmd IDENTIFY: gedis server sends epoch and signed epoch to client (signed with pub key of 3bot running gedis) returns; serialized_in_format([epoch,3botid, signature])
- cmd PHONEBOOK_GET(3botid) -> returns  serialized_in_format([data_serialized_in_format,data_signature]) data is the phonebook data
- this allows client to call the phonebook (using PHONEBOOK_GET) to verify the server
- cmd AUTHORIZE(3botid, signature):
    - user authorizes when opening connection
    - signature is done with priv key user
    - allows gedis server to know who is the user
- how to send commands
    -  CMD = COMMAND ... like before
    - send JSON or MSGPACK serialized [$3botid,$PAYLOAD,$SIGNATURE] 
    - commands are send encrypted/signed from client then $SIGNATURE used
- whatever result from the current gedis calls (like done in JSX) are being encrypted with public key of the person who opens the connection & signed with priv key of 3bot server
   - [$3botid_server, $PAYLOAD, $SIGNATURE] 
 

```python
[serialized_data_encrypted, signature_of_data_after_decryption]
```

## todo 

- [ ] move specs to right location
- [ ] call gedis actors with commands (like today)
- [ ] be able to specify the return format (std msgpack) also support json
- [ ] ...

**Comment by despiegk** [comment]
in jumpscale config add

- THREEBOT_ID
- THREEBOT_NAME

**Comment by alichaddad** [comment]
Sample use case(branch: development latest):
```
# add sample configuration
j.core.myenv.config['THREEBOT_ID'] = 5 

# start threebot server
threebot = j.servers.threebot.get()
threebot.start()

# get client to the server
client = j.clients.gedis.get(name='main_gedis_threebot', port=8901)
client.actors.base.identify()

```

**Comment by zgorizzo69** [comment]
### Description

- 3bots are running a **Gedis server** that accepts **REDIS Command**
- The **phonebook** list all the registered 3botid alongside their pubkey and their IP
- here after when we are talking about a user (or client) we mean an external user that has a **3bot ID and the priv key** that correponds to that 3botid
- the server is a 3bot that also has a 3bot_id the corresponding priv key and that host a GEDIS server

### Stories

* As a user I want to be able to setup an secure connection with the  GEDIS server  
We first need to `IDENTIFY` the server and then `AUTHORIZE` the connection

  - a user will be able to call gedis command **`IDENTIFY`** with his 3bot_id and a nonce the server will answer with the nonce, its server_3botID, the user_3botid and the signature of the nonce+server_3botid+user_3botid that we can validate against the pubkey that is linked to the 3botid (that comes from the phonebook). 
The result will be in a particular format see `FORMAT_CONFIGURE`

```
IDENTIFY user_3botid, nonce
response=  serialized_in_format([nonce,server_3botid, user_3botid,
 signature(OF:nonce+server_3botid+user_3botid, WITH:server_3botid_PRIVKEY)])
```

-  - a user will to be able to call gedis command **`AUTHORIZE`** in order to get authorized and identified by the server. 
`AUTHORIZE` will take as parameter a  signed `IDENTIFY` answer by himself that contains the user 3bot_id that is calling (param1 here below) and the signature of that parameter with the privkey  of the user 3botid
The server will store a trace with a user object that corresponds to an open to the user IP and its 3botID.
```
AUTHORIZE param1=[nonce,server_3botid, user_3botid, 
            signature(OF:nonce+server_3botid+user_3botid, WITH:server_3botid_PRIVKEY)],
      signature(OF:param1, WITH:user_3botid_PRIVKEY)

response= serialized_in_format( [server_3botid,
ENCRYPT(WITH:user_3botid_PUBKEY, DATA=OK/NOK) , 
signature(OF:payload not encrypted, WITH:server_3botid_PRIVKEY)])
```
**WARNING** We should keep track of the param1 used to open a connection and never reuse it to avoid replay attack. We could also add a timestamp and check that time elapsed since the IDENTIFY call.
We need the user to sign a message that is already signed by the server otherwise if I have a signed message by a 3bot I can use it to impersonate him. We need this two layer of signatures and encryption to avoid replay attack.
 
 * As a user I want to be able to call gedis command 
**`FORMAT_CONFIGURE`** in order to set a serialization format. We can pass either JSON or  MSGPACK as parameter
```
FORMAT_CONFIGURE JSON
response= OK
FORMAT_CONFIGURE MSGPACK
response= OK
```
No encryption nor signature needed here 

* As a user I want to be able to call gedis command **`PHONEBOOK_GET`** for a specific 3botid=asked_3botid. It will answer with the corresponding section of data on the phonebook data that lives on bcdb. This is needed to retrieve the information like the pubkey related to a 3botid. This data includes a signature of the data with the pubkey mentioned in the data  
```
PHONEBOOK_GET some_3botid
response=serialized_in_format(
[data_serialized_in_format,data_signature]) 
```
data is the phonebook data
 
* As a user I want to send command via GEDIS  that are defined in the actors that the 3bot have loaded. To be able to send commands we **need to be authorized** see below.
We have to pass encrypted the COMMAND encrypted for the server and signed with the user_3bot_id  
```
command= [user_3botid,
ENCRYPT(WITH:server_3botid_PUBKEY, WHATEVER_COMMAND_NAME, WHATEVER_COMMAND_PAYLOAD) , 
signature(OF:all the previous, WITH:user_3botid_PRIVKEY)]
response= serialized_in_format( [server_3botid,
ENCRYPT(WITH:user_3botid_PUBKEY, WHATEVER_ANSWER_PAYLOAD) , 
signature(OF:payload not encrypted, WITH:server_3botid_PRIVKEY)])
```
send JSON or MSGPACK serialized [$3botid,$PAYLOAD,$SIGNATURE]
commands are send encrypted/signed from client then $SIGNATURE used
whatever result from the current gedis calls (like done in JSX) are being encrypted with public key of the person who opens the connection & signed with priv key of 3bot server
[$3botid_server, $PAYLOAD, $SIGNATURE] 

* The server should know who he is so we need to add that parameters in jumpscale config 
```
THREEBOT_ID
THREEBOT_PHONEBOOK_ADDR = 'localhost'
```

### Problems 

- A man-in-the-middle can learn the public key of either peer and know that they are interacting. Also it could do a replay attack for the authorize method if the server doesn't keep track of his nonce
- Recording a user’s network traffic and then later stealing their secret key will allow an attacker to decrypt their past connections.

We could solve those problems by using nacl_scalarmult and ephemeral keys. Indeed the user already know the server pubkey as it connects to it so we could generate a shared secret based on server_pub_key and client_privkey for the client side and client_pubkey and server_privkey for the server side. To obfuscate who is talking to who and prevent traffic replay if priv_key is lost we could use ephemeral key pairs on both side and then delete it when the connection is closed.

**Comment by zaibon** [comment]
> AUTHORIZE param1=[nonce,server_3botid, user_3botid, 
            signature(OF:nonce+server_3botid+user_3botid, WITH:server_3botid_PRIVKEY)],

I think there is a mistake in the signature definition, the signature of the AUTHORIZE command needs to be done using the `user_3botid_PRIVKEY` not the `server_3botid_PRIVKEY`

**Comment by zaibon** [comment]
I have a question regarding the new command   `FORMAT_CONFIGURE ($format)`
In the current implementation of gedis, there is a system of headers that deals with content type negotiation:
https://github.com/threefoldtech/jumpscaleX_core/blob/1e61db859e5b743fec1e1ca02793991501bedb0a/JumpscaleCore/servers/gedis/handlers.py#L347-L356
https://github.com/threefoldtech/jumpscaleX_core/blob/1e61db859e5b743fec1e1ca02793991501bedb0a/JumpscaleCore/servers/gedis/handlers.py#L425-L439

Does this means this concept of headers needs to be removed ?

**Comment by zaibon** [comment]
Second remark regarding this "secure protocol" It seems it expects that gedis now keeps the TCP connection open for as long as the communication is going on since we will want to avoid redoing the pretty expensive handshake procedure. Shouldn't we have a system of "keep alive" to ensure the idle TCP connection is not closed by the OS?

**Comment by despiegk** [comment]
lets first implement the required primitives here
/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/tools/threebot/

**Comment by zgorizzo69** [comment]
so the primitives were basically the functions `deserialize_check_decrypt()` and `serialize_sign_encrypt()` in `ThreebotToolsFactory`
I implemented them in this [commit](https://github.com/threefoldtech/jumpscaleX_core/commit/361567ec07918776e6ca1f5da5ee3332ab0abf3d)

**Comment by despiegk** [comment]
this has been implemented, see the examples in tutorial
